openapi: 3.0.4
info:
  title: Payment Service API
  description: API сервиса платежей
  version: 1.0.0
paths:
  /payments/create/{userId}:
    post:
      security:
        - Bearer: [ ]
      tags:
        - payments
      parameters:
        - $ref: '#/components/parameters/UserId'
      summary: Кладет на счет 5000 (если счета нет, то он создается)
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
        '500':
          description: Внутреняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /payments/balance/{userId}:
    get:
      security:
        - Bearer: [ ]
      tags:
        - payments
      parameters:
        - $ref: '#/components/parameters/UserId'
      summary: Получить баланс на счете
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
        '500':
          description: Внутреняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /payments/process/{userId}:
    post:
      security:
        - Bearer: [ ]
      tags:
        - payments
      parameters:
        - $ref: '#/components/parameters/UserId'
      summary: Оплатить заказ
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProcessPaymentRequest'
      responses:
        '200':
          description: Платеж успешно проведен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
        '402':
          description: Недостаточно средств на счете для совершения платежа
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутреняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /payments/deposit/{userId}:
    post:
      security:
        - Bearer: [ ]
      tags:
        - payments
      parameters:
        - $ref: '#/components/parameters/UserId'
      summary: Положить деньги на счет
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepositMoneyRequest'
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
        '500':
          description: Внутреняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
tags:
  - name: payments
    description: Платежные операции

components:
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
      description: >-
        Enter the token with the `Bearer: ` prefix, e.g. "Bearer abcde12345".
  parameters:
    UserId:
      name: userId
      in: path
      required: true
      description: Идентификатор пользователя
      schema:
        type: integer
        format: int64
  schemas:
    BalanceResponse:
      description: остаток на счете
      type: object
      properties:
        money:
          type: integer
          example: 100
    ProcessPaymentRequest:
      type: object
      required:
        - order_sum
      properties:
        order_sum:
          type: integer
          example: 100
    DepositMoneyRequest:
      type: object
      required:
        - money
      properties:
        money:
          type: integer
          example: 100
    ErrorResponse:
      description: описание ошибки
      type: object
      properties:
        message:
          type: string
          example: Внутреняя ошибка сервера