server:
  port: 8090
spring:
  application:
    name: payments
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://pg_payments/payments
    username: sa
    password: password
  jpa:
    show-sql: false
  liquibase:
    url: jdbc:postgresql://pg_payments/payments
    user: sa
    password: password
    change-log: classpath:/db/changelog/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/master