FROM amazoncorretto:21 as builder

WORKDIR app
COPY . .

RUN ./gradlew :storefront:clean :storefront:bootJar

FROM amazoncorretto:21

COPY --from=builder /app/storefront/build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["/app.jar"]