spring:
  application:
    name: shop
  r2dbc:
    url: r2dbc:postgresql://localhost/shop
    username: sa
    password: password
  jpa:
    show-sql: false
  liquibase:
    url: jdbc:postgresql://localhost/shop
    user: sa
    password: password
    change-log: classpath:/db/changelog/db.changelog-master.xml
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
storage-path: ./storage
payments-service-uri: http://localhost:8090