spring:
  application:
    name: shop
  liquibase:
    url: jdbc:postgresql://localhost/test
    user: sa
    password: password
    change-log: classpath:/db/changelog/db.changelog-master.xml
storage-path: ./storage
payments-service-uri: http://localhost:8090